language: python
python: '3.7'
script: python setup.py bdist_wheel
deploy:
  provider: pypi
  user: "__token__"
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: D+ODloPmwWziOhPhmVgGAji/QtS3SoG0PdLSqwI3Uv8M/PeExig+QQ1tNGY75XWT8oPFxBld+rSgfYBx5oIUPdIyCYj+Oe4fhn4jgCCG0d/MsM4zXS98epyJ1KbqiCprNCq0HN1U8JUT0RZxBCwjNFr0EigdgsfVuRbwu+esqJZ6mpS4FZ8oli6V44PNJCOxUjtjS2c7CbP61tVbgSgdl95dwuH/V7izh9OZtjYIKoN8n+nABZLUTTuUz0muKHmBhwCFO5KZ+nVQKh+FwlknFWKeodTw4bWgBnHvCy6XrZYBZvmR/vXLInthEPYNuiWsiBYgbtEWczYUhvO4mDLTN7FFbNhDQyC6v+Dl8+dVmQ9y6UOUJ1K1cYc5l9vljJsVPCT2KenUvsrramK6H+lPKc5ys5d+U7hVOzcpCRbLVdfllUHFKJ+ZlsViFBDQA1yuLiItT3fHw1vwtAHsz2jsDnoHgZ9oc55jH21pQaIE11d8SqSH9LDU7iW5Sc3SYoKZKOZEP5lU73DzErsexPodQ83++SCw8zHfzoZbPw9I29/15UAZG5/lHeGWRudrIWv7mgLCafN53H6ZPhko+tNmUTuA56Ro+rJ9ijXyQPTmXOSKKT4NUI751ADmEI6pRtQpHqyceFMfK926sSjGX4RTHyh+wR6I7RhHpdJ0SP21LNA=
